version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  anveshak-neo:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["python", "run.py"]

volumes:
  postgres_data:
